<?php
define('AT_INCLUDE_PATH', '../../include/');
require (AT_INCLUDE_PATH.'vitals.inc.php');
admin_authenticate(AT_ADMIN_PRIV_MANAGE_MULTI);

include(AT_INCLUDE_PATH . 'install/install.inc.php');
include(AT_INCLUDE_PATH . 'classes/sqlutility.class.php');
include('include/config_multisite_template.php');

if ($_POST['submit']){
	global $msg;
	if (!file_exists(MM_MULTISITE_CONFIG_FILE)) {
		$msg->addError(array('CONFIG_FILE_NOT_EXIST', MM_MULTISITE_CONFIG_FILE));
	} else if (!is_writeable(MM_MULTISITE_CONFIG_FILE)) {
		$msg->addError(array('FILE_NOT_WRITABLE', MM_MULTISITE_CONFIG_FILE));
	}
	
	if (!$msg->containsErrors()) {
		// create database to manage multisite
		create_and_switch_db($_POST['db_host'], $_POST['db_port'], $_POST['db_login'], $_POST['db_password'], $_POST['tb_prefix'], $_POST['db_name']);
		
		$sqlUtility = new SqlUtility();
		$sqlUtility->queryFromFile('include/atutor_multisite_schema.sql', $addslashes($_POST['tb_prefix']));
		
		// switch to the main database
		@mysql_select_db(DB_NAME, $db);
	
		// database is created successfully
		if (!$msg->containsErrors()) {
			// write config file for managing multisite
			$comments = '/*'.str_pad(' This file was generated by the ATutor '.VERSION. ' managing multi-site script.', 70, ' ').'*/' . "\n" .
			            '/*'.str_pad(' File generated '.date('Y-m-d H:m:s'), 70, ' ').'*/';
			
			if (!write_MM_MULTISITE_CONFIG_FILE(MM_MULTISITE_CONFIG_FILE, $_POST['db_login'], $_POST['db_password'], 
			    $_POST['db_host'], $_POST['db_port'], $_POST['db_name'], $_POST['tb_prefix'], $comments)) {
				$msg->addError(array('FILE_NOT_WRITABLE', MM_MULTISITE_CONFIG_FILE));
			}
			
			@chmod(MM_MULTISITE_CONFIG_FILE, 0444);
			
			$msg->addFeedback(array('FILE_CREATED', MM_MULTISITE_CONFIG_FILE));
			$msg->addFeedback('ACTION_COMPLETED_SUCCESSFULLY');
		}
	}
} else if (file_exists(MM_MULTISITE_CONFIG_FILE)) {
	
	include(MM_MULTISITE_CONFIG_FILE);
	if (defined('DB_NAME_MULTISITE')) {
		$msg->addWarning(array('MANAGE_MULTISITE_DB_EXISTS', DB_NAME_MULTISITE));
	}
}

require (AT_INCLUDE_PATH.'header.inc.php');

$msg->printAll();

?>

<div class="input-form">
<h2>Setup Subsite Database</h2>
<p><?php echo _AT('config_multi_desc'); ?></p>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>"  name="setup_multi" method="post" class="form_input">
	<table cellspacing="0" cellpadding="1" border="0">
	<tr>
		<td><span class="required" title="Required Field">*</span><b><label for="db">Database Hostname:</label></b><br />
			Hostname of the database server. Default: <kbd>localhost</kbd></td>
		<td valign="middle"><input type="text" name="db_host" id="db" value="<?php if (!empty($_POST['db_host'])) { echo stripslashes(htmlspecialchars($_POST['db_host'])); } else { echo DB_HOST; } ?>" class="formfield" /></td>
	</tr>
	<tr>
		<td><span class="required" title="Required Field">*</span><b><label for="port">Database Port:</label></b><br />
			The port to the database server. Default: <kbd>3306</kbd></td>
		<td><input type="text" name="db_port" id="port" value="<?php if (!empty($_POST['db_port'])) { echo stripslashes(htmlspecialchars($_POST['db_port'])); } else { echo DB_PORT; } ?>" class="formfield" /></td>
	</tr>
	<tr>
		<td><span class="required" title="Required Field">*</span><b><label for="username">Database Username:</label></b><br />
			The username to the database server.</td>
		<td><input type="text" name="db_login" id="username" value="<?php echo stripslashes(htmlspecialchars($_POST['db_login'])); ?>" class="formfield" /></td>
	</tr>
	<tr>
		<td><span class="required" title="Required Field">*</span><b><label for="pass">Database Password:</label></b><br />
			The password to the database server.</td>
		<td><input type="text" name="db_password" id="pass" value="<?php echo stripslashes(htmlspecialchars($_POST['db_password'])); ?>" class="formfield" /></td>
	</tr>
	<tr>
		<td><span class="required" title="Required Field">*</span><b><label for="name">Database Name:</label></b><br />
			The name of the database to use. It will be created if it does not exist.<br />Default: <kbd>ATutor_manage_multisite</kbd></td>
		<td><input type="text" name="db_name" id="name" value="<?php if (!empty($_POST['db_name'])) { echo stripslashes(htmlspecialchars($_POST['db_name'])); } else { echo 'ATutor_manage_multisite'; } ?>" class="formfield" /></td>
	</tr>
	<tr>
		<td><div class="optional" title="Optional Field">?</div><b><label for="prefix">Table Prefix:</label></b><br />
			The prefix to add to table names to avoid conflicts with existing tables.<br />
			Default: <kbd>AT_</kbd></td>
		<td><input type="text" name="tb_prefix" id="prefix" value="<?php if (!empty($_POST['tb_prefix'])) { echo stripslashes(htmlspecialchars($_POST['tb_prefix'])); } else { echo TABLE_PREFIX; } ?>" class="formfield" /></td>
	</tr>
	</table>

	<input type="submit" name="submit" />
</form>
</div>


<?php
require (AT_INCLUDE_PATH.'footer.inc.php');
?>